import './globals.css'
import './fonts.css'

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Victor Santos',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}